sudo: required
os:
- linux
- windows
services:
- docker
cache:
  directories:
  - "$HOME/.cache"
language: C
env:
  matrix:
  - OS=el DIST=6
  - OS=el DIST=7
  - OS=fedora DIST=27
  - OS=fedora DIST=26
  - OS=Windows VISUAL_STUDIO="Visual Studio 15 2017" JANSSON_LIB="jansson.lib" ARCH=x86
  - OS=Windows VISUAL_STUDIO="Visual Studio 15 2017 Win64" JANSSON_LIB="janssonx64.lib" ARCH=x64
matrix:
  exclude:
  - os: windows
    env: OS=el DIST=6
  - os: windows
    env: OS=el DIST=7
  - os: windows
    env: OS=fedora DIST=27
  - os: windows
    env: OS=fedora DIST=26
  - os: linux
    env: OS=Windows VISUAL_STUDIO="Visual Studio 15 2017" JANSSON_LIB="jansson.lib" ARCH=x86
  - os: linux
    env: OS=Windows VISUAL_STUDIO="Visual Studio 15 2017 Win64" JANSSON_LIB="janssonx64.lib" ARCH=x64
script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then git submodule update --init --recursive; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then git describe --long || true; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then git clone https://github.com/packpack/packpack.git packpack; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then packpack/packpack; fi
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then sh -xe travisWinBuild.sh; fi
before_deploy:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mkdir deploy && cp build/*.rpm deploy/; fi
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then cd deploy && 7z a -sdel libredfish-$TRAVIS_TAG-$ARCH.zip *; fi
deploy:
  provider: releases
  api_key:
    secure: hu4VIQCve/qYtR65lJ67HEFuhKC7XOQL/G1wzVsAgZ2ImyxlMsphPIRZQxgQSRAbp5AkxPGS7tYELmZHXhae2je0O7fqbEbWin7DmtMFLWgxeDyDJkWDXnkdznvOAS4t7DgDL8bFAEhCxkmqYEzHbMcpdjGi2BsW9QeoyXr9SuWKv+AmRmh/KY3U8qTzzcEwYNP0grkdyrJHI95pZeUBsHxgrAmk3Mo2m6DTrwyLcQk068fvKNBlHeijOXoLaCExOnoi1UCoe5HkESkqjrEV73gnlQf3CA69vLeMUa20mHLkRJqLduKElRA3If+t7WYgwVZzlg5l71S1eIRppkkUJ09PsZT20ONqvJt4YE57lpG8SxDn7tU5ZdeOnvM7tnoKqvGR0+R6iOO/LXngbdbewzVI23iqW8tJ5acyuxkrBeSNSvg3h/TtZE/Zc7kHPM6mztZ5a9GQIywOh6JLQ4cKfbFnS7ZUdExwepeuUAaS+VqiYOwJzJvv3+G90qqKBA6rnXOVdnjtzBbrsY/714cuui2i06oKq4mdycV4DHhDk1UOBj1fCy/QOGMUt77wGd+vz8d1sP5jWZTwZLDJDzY+2kTZki6Qs+nJAGT6fLs+4Mxx5Xyb1OYx26auFIAjmxqACcabbshB7cK1abeRD/+yLRWT7H8+0lr+2/kAJvIzyWk=
  file_glob: true
  file: deploy/*
  skip_cleanup: true
  on:
    tags: true
