sudo: required
services:
  - docker

cache:
    directories:
     - $HOME/.cache

language: C

env:
    matrix:
      - OS=el DIST=6
      - OS=el DIST=7
      - OS=fedora DIST=27
      - OS=fedora DIST=26
      #- OS=ubuntu DIST=trusty
      #- OS=ubuntu DIST=precise
      #- OS=ubuntu DIST=xenial
      #- OS=ubuntu DIST=yakkety
      #- OS=debian DIST=jessie
      #- OS=debian DIST=wheezy
      #- OS=debian DIST=stretch
      #- OS=ubuntu DIST=xenial ARCH=i386
      #- OS=debian DIST=jessie ARCH=i386

script:
 - git submodule update --init --recursive
 - git describe --long || true
 - git clone https://github.com/packpack/packpack.git packpack
 - packpack/packpack
