sudo: required
os:
- linux
- windows
services:
- docker
cache:
  directories:
  - "$HOME/.cache"
language: C
env:
  matrix:
  - OS=el DIST=6
  - OS=el DIST=7
  - OS=fedora DIST=29
  - OS=fedora DIST=28
  - OS=Windows VISUAL_STUDIO="Visual Studio 15 2017" JANSSON_LIB="jansson.lib" ARCH=x86
  - OS=Windows VISUAL_STUDIO="Visual Studio 15 2017 Win64" JANSSON_LIB="janssonx64.lib" ARCH=x64
matrix:
  exclude:
  - os: windows
    env: OS=el DIST=6
  - os: windows
    env: OS=el DIST=7
  - os: windows
    env: OS=fedora DIST=29
  - os: windows
    env: OS=fedora DIST=28
  - os: linux
    env: OS=Windows VISUAL_STUDIO="Visual Studio 15 2017" JANSSON_LIB="jansson.lib" ARCH=x86
  - os: linux
    env: OS=Windows VISUAL_STUDIO="Visual Studio 15 2017 Win64" JANSSON_LIB="janssonx64.lib" ARCH=x64
script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then git clone https://github.com/packpack/packpack.git packpack; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then VERSION=${TRAVIS_TAG} packpack/packpack; fi
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then sh -xe travisWinBuild.sh; fi
before_deploy:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then rm -f build/*debuginfo* && rm -f build/*debugsource*; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mkdir deploy && cp build/*.rpm deploy/; fi
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then cd deploy && 7z a -sdel libredfish-$TRAVIS_TAG-$ARCH.zip * && cd ..; fi
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then sleep 5 && ls deploy/*; fi
deploy:
  provider: releases
  api_key:
    secure: LNWUKIy9oMjMeVW9CJgNcTkg/TTeqjTAidfkxknXnzuUNIQ/+5AFtucT0JsF7GU3WfHnwQjr5G979hSsCwU/ANxlO+Wk4oxYLF/chpQtK0xgKJK0DTZaGf5MgunrZuZtazb1SCQ1VK5gvzuwA45EZUD8R8scC0xHyPyjcU0K6seVD0lMpYs0KzaUX7cWHa5tB6apk3ZFqWixjWVIiQq/WdWC/u/YQAvDe8xbjLE2QwiTbCUJNDpzY3Hwd/bd2M7PQBd0pkXbXJasQ7G7wFxDqxBt2fHXQOWKVo37AolqwUH0/hsHMhT4YHmR6qcmVZ2QYGl9Ryi73mPtrRlC6tA/v4LIoLadDttvld48x8wcLtaYkPUGzHFqfoU2y4oR/bqsjseLBX1kHA2S/a7mrXUKkZizkPloHScoJLum0m3vz1UP/wIjyA7L7w9cm+Lxi0IM0DyINX1EG24tsy6WeHoNW2QWJlgY5ewgwNwzpwx7djO2u7Jl9rHKLa53wrfBxn+KxfbDmN+M0T56Obe7lBQgivSYqNOyGobK63jhGsQAvyy5d9o2ePoM8hnDTst0lLXercvJwFFj0y5v/pqEOBXUmajhP5nqD0NFTSL0+impghY1MtZpxpLa0JM4XHn9egeLCq8A+daTTXeXkACEhBKk9HtMV2uj+tUIwwCSvcYFlFE=
  file_glob: true
  file: deploy/*
  skip_cleanup: true
  on:
    tags: true
