sudo: required
env:
  matrix:
  - OS_TYPE=centos OS_VERSION=6
  - OS_TYPE=centos OS_VERSION=7
  
services:
  - docker

before_install:
 - sudo apt-get update
 - sudo apt-get install -y libjansson-dev
  
script:
    ############################################################################
    # Build main and tests
    ############################################################################
    - mkdir -p build
    - cd build
    - cmake .. 
    - make
